Description of alea
Home > ODEm > alea.m
alea
PURPOSE
ODEm - Optimal Design Experiments with Matlab
SYNOPSIS
function r = alea (a,b)
DESCRIPTION
 ODEm - Optimal Design Experiments with Matlab
 Ricardo García Rodenas, José Ángel Martín Baos, José Carlos García García
 Department of Mathematics, Escuela Superior de Informática. University of
 Castilla-La Mancha. Ciudad Real, Spain.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
SPSO2011_NM Standard PSO 2011
alea_normal Use the polar form of the Box-Muller transformation to obtain a pseudo
alea_sphere ******* Random point in a hypersphere ********
SOURCE CODE
function r = alea (a,b)
% ODEm - Optimal Design Experiments with Matlab
% Ricardo García Rodenas, José Ángel Martín Baos, José Carlos García García
% Department of Mathematics, Escuela Superior de Informática. University of
% Castilla-La Mancha. Ciudad Real, Spain.
% Random real  number between a and b
    r = a + rand*(b - a);
end