Description of alea_sphere
Home > ODEm > alea_sphere.m
alea_sphere
PURPOSE
******* Random point in a hypersphere ********
SYNOPSIS
function [x] = alea_sphere(D, radius)
DESCRIPTION
  ******* Random point in a hypersphere ********
 Put  a random point inside the hypersphere S(0,radius) (center 0, radius 1).
 Uniform distribution % Developed by: Maurice Clerc (May 2011)
CROSS-REFERENCE INFORMATION
This function calls:
alea ODEm - Optimal Design Experiments with Matlab
alea_normal Use the polar form of the Box-Muller transformation to obtain a pseudo
This function is called by:
SPSO2011_NM Standard PSO 2011
SOURCE CODE
function [x] = alea_sphere(D, radius)
%  ******* Random point in a hypersphere ********
% Put  a random point inside the hypersphere S(0,radius) (center 0, radius 1).
% Uniform distribution % Developed by: Maurice Clerc (May 2011)
x = zeros(1,D); %**
% --------- Step 1. Direction
l = 0;
for j=1:1:D
   % x(j) = randn; %?
    x(j)=alea_normal(0,1); %**
    l = l + x(j)*x(j);
end
l=sqrt(l);
% --------- Step 2. Random radius
r=alea(0,1);
x= r*radius*x/l;
end